spring:
  datasource:
    url: jdbc:h2:mem:heydev
    user: sa
    password:
    driverClassname: org.h2.Driver
  jpa:
    spring:
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /db-console
      settings:
        trace: false
        web-allow-others: false 
  profiles:
    active: prod